shared:
  annotations:
    screwdriver.cd/executor: queue
jobs:
  main:
    image: centos:centos7
    requires: [ ~commit, ~pr ]
    steps:
      - cpu: echo $CONTAINER_CPU_LIMIT
      - memory: echo $CONTAINER_MEMORY_LIMIT
      - env: printenv
