shared:
  image: centos:centos7
  annotations:
    screwdriver.cd/executor: k8s

jobs:
  micro:
    annotations:
      screwdriver.cd/cpu: MICRO
      screwdriver.cd/ram: MICRO
    requires: [ ~commit, ~pr ]
    steps:
      - printenv: printenv
      - cpu: echo $CONTAINER_CPU_LIMIT
      - memory: echo $CONTAINER_MEMORY_LIMIT

  low:
    annotations:
      screwdriver.cd/cpu: LOW
      screwdriver.cd/ram: LOW
    requires: [ ~commit, ~pr ]
    steps:
      - printenv: printenv
      - cpu: echo $CONTAINER_CPU_LIMIT
      - memory: echo $CONTAINER_MEMORY_LIMIT
